name: 'INSTALL:DEPENDENCIES'
description: 'Install Dependencies for Running Jobs'
inputs:
  github_token:
    description: "github token to use to call the api"
    required: true
  cpu_architecture:
    description: "CPU architecture"
    required: false
    default: "amd64"
  skip_python:
    description: "Skip Python installation"
    required: false
    default: "false"
  skip_aws_cli:
    description: "Skip AWS CLI installation"
    required: false
    default: "false"
  skip_docker_compose:
    description: "Skip Docker Compose installation"
    required: false
    default: "false"
  skip_go:
    description: "Skip Go installation"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v4
      if: ${{ inputs.skip_go == 'false' }}
      with:
        go-version: '1.19.0'
        cache: false

    - uses: actions/setup-python@v4
      if: ${{ inputs.skip_python == 'false' }}
      with:
        python-version: 'pypy3.9'

    - uses: chrisdickinson/setup-yq@latest

    - id: install-aws-cli
      if: ${{ inputs.skip_aws_cli == 'false' }}
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2
        arch: ${{ inputs.cpu_architecture }}

    - name: Dependencies.
      shell: bash
      if: ${{ inputs.skip_docker_compose == 'false' }}
      run: |
        sudo apt-get update
        sudo apt-get install wget jq -y

    - name: Install Docker Compose
      if: ${{ inputs.skip_docker_compose == 'false' }}
      shell: bash
      run: |
        sudo apt-get update || echo "Issue running apt-get update."
        sudo apt-get install \
          ca-certificates \
          curl \
          gnupg \
          lsb-release -y || echo "issue installing dependencies"
        sudo mkdir -p /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --no-tty --batch --dearmor --yes -o /etc/apt/keyrings/docker.gpg
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update || echo "Issue running apt-get update."
        sudo apt-get install docker-compose-plugin -y || echo "Issue installing docker compose"
