name: check-gentx

on:
  push:
    branches:
      - main
      - ci-fix-validator
  pull_request:
    branches:
      - main
      - ci-fix-validator
    paths:
      - "genesis_files/**"

env:
  ZETACORED_BINARY: "https://github.com/zeta-chain/node/releases/download/v10.0.7/zetacored-ubuntu-22-amd64"
  ZETACLIENT_BINARY: "https://github.com/zeta-chain/node/releases/download/v10.0.7/zetacored-ubuntu-22-amd64"
  CHAINID: "zetachain_7000-1"
  KEYRING: "test"
  HOSTNAME: checker

jobs:
  check-gentx:
    runs-on: ["ubuntu-22.04"]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Restore Cached Binary
        uses: actions/cache/restore@v3
        id: restore-cache
        with:
          path: /usr/bin/zetacored
          key: ${{ runner.os }}-zetacored-${{ hashFiles('zetacored') }}

      - name: Download Zetacored
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          echo "Downloading Latest Zetacored From $ZETACORED_BINARY"
          wget $ZETACORED_BINARY -O zetacored
          sudo mv zetacored /usr/bin/zetacored
          sudo chmod +x /usr/bin/zetacored
          zetacored version

      - name: Validate GentX and OS_INFO files
        run: |
          rm -rf ~/.zetacored/ || true
          zetacored init Zetanode --chain-id=$CHAINID
          cat "$HOME"/.zetacored/config/genesis.json | jq '.app_state["staking"]["params"]["bond_denom"]="azeta"' > "$HOME"/.zetacored/config/tmp_genesis.json && mv "$HOME"/.zetacored/config/tmp_genesis.json "$HOME"/.zetacored/config/genesis.json
          cat "$HOME"/.zetacored/config/genesis.json | jq '.app_state["crisis"]["constant_fee"]["denom"]="azeta"' > "$HOME"/.zetacored/config/tmp_genesis.json && mv "$HOME"/.zetacored/config/tmp_genesis.json "$HOME"/.zetacored/config/genesis.json
          cat "$HOME"/.zetacored/config/genesis.json | jq '.app_state["gov"]["deposit_params"]["min_deposit"][0]["denom"]="azeta"' > "$HOME"/.zetacored/config/tmp_genesis.json && mv "$HOME"/.zetacored/config/tmp_genesis.json "$HOME"/.zetacored/config/genesis.json
          cat "$HOME"/.zetacored/config/genesis.json | jq '.app_state["mint"]["params"]["mint_denom"]="azeta"' > "$HOME"/.zetacored/config/tmp_genesis.json && mv "$HOME"/.zetacored/config/tmp_genesis.json "$HOME"/.zetacored/config/genesis.json
          cat "$HOME"/.zetacored/config/genesis.json | jq '.app_state["evm"]["params"]["evm_denom"]="azeta"' > "$HOME"/.zetacored/config/tmp_genesis.json && mv "$HOME"/.zetacored/config/tmp_genesis.json "$HOME"/.zetacored/config/genesis.json
          cat "$HOME"/.zetacored/config/genesis.json | jq '.consensus_params["block"]["max_gas"]="10000000"' > "$HOME"/.zetacored/config/tmp_genesis.json && mv "$HOME"/.zetacored/config/tmp_genesis.json "$HOME"/.zetacored/config/genesis.json
          cat "$HOME"/.zetacored/config/genesis.json | jq '.app_state["gov"]["voting_params"]["voting_period"]="10s"' > "$HOME"/.zetacored/config/tmp_genesis.json && mv "$HOME"/.zetacored/config/tmp_genesis.json "$HOME"/.zetacored/config/genesis.json

          mkdir -p ~/.zetacored/os_info  ~/.zetacored/config/gentx/
          cp -a genesis_files/gentx/* ~/.zetacored/config/gentx/

          for file in genesis_files/gentx/* ; do
            echo "Processing file: ${file}"
            ADDRESS=$(jq '.body.messages[0].delegator_address'  -r $file)
            zetacored add-genesis-account $ADDRESS 10000000000000000000azeta
          done

          zetacored collect-observer-info
          zetacored add-observer-list
          zetacored collect-gentxs
          zetacored validate-genesis

          # If the above command fails, the job will fail
          if [ $? -eq 0 ]; then
            echo "SUCCESS"
            echo "gentx and OS_INFO files are valid"
            exit 0
          else
            echo "FAILURE"
            echo "gentx and OS_INFO files are invalid"
            exit 1
          fi

      - name: Check Security Contact Is Completed
        run: |

          for file in genesis_files/gentx/* ; do
            echo "Processing file: ${file}"
            SECURITY_CONTACT=$(jq '.body.messages[0].description.security_contact'  -r $file | tr -d '[:space:]'                                                          ) 
            echo $SECURITY_CONTACT
            echo $SECURITY_CONTACT | grep -E -q '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}' 
            
            if [ $? -eq 0 ]; then
              echo "SUCCESS - Security Contract Email Found"
              exit 0
            else
              echo "No Security Contract Email Found"
              exit 1
            fi
            done


      - name: Start Zetacored
        run: |
          zetacored start --trace \
          --minimum-gas-prices=0.0001azeta \
          --json-rpc.api eth,net,web3 \
          --api.enable >> ~/.zetacored/zetacored.log  &

          sleep 8
          latest_block_height=$(curl --request GET -sL --url 'localhost:26657/status' --header 'Content-Type: application/json' | jq '.result.sync_info.latest_block_height|tonumber')

          if [ "$latest_block_height" -ge 0 ]; then
              echo "SUCCESS"
              echo "zetacored started successfully"
              exit 0
          else
            echo "FAILURE"
            echo "zetacored failed to start"
            exit 1
          fi

      - name: Save Binary To Cache
        uses: actions/cache/save@v3
        if: steps.restore-cache.outputs.cache-hit != 'true'
        with:
          path: /usr/bin/zetacored
          key: ${{ runner.os }}-zetacored-${{ hashFiles('zetacored') }}
